### ISSUE TITLE
Trying to understand how it works but can't.

### ISSUE THREAD

**Issue by vktsn0303** [ruoxi-wang/BBFMM3D#3]
I've been trying to figure out how I can access the output of the program. The README file says that the stress.bin file contains the output but when I open that in MATLAB (I don't know how else to open it) I only see two columns of data which could probably mean that only two components, of whatever it is the matrix vector product is calculating, are present. So, it would be nice if someone could please help me understand how this works: If I were to calculate an induced potential using a particular kernel that I would be defining, in 3D, how do I access the three components of the induced vector. Where are they stored? And would I have to change any part of the library to perform my calculations or does this library calculate the matrix vector product on the definition of a kernel by itself? I tried reading the paper  'The black-box fast multipole method' by Dave _et al_ but couldn't understand it at all. Also, I know only the basics of C++ (I try to use it like the way I use MATLAB. Don't know anything about defing classes and such. My apologies.) So please help me understand using this library in the most easiest way possible, step-by-step. It doesn't matter even if there are a 100 steps that I need to follow, please help.

**Comment by vktsn0303** [comment]
Can someone at least provide a pseudo code (flowchart) of compute.hpp?

**Comment by ruoxi-wang** [comment]
Hi,

I am trying to understand your question. By "three components of the
induced vector", what is induced vector by your definition and what are the
three components? The BBFMM3D code is supposed to calculate a matrix
product K * v and output the result, where K_ij = k(xi, xj), k(.,.) is your
kernel function in 3D, and xi is your data point in 3D. If K is of size n
by n and v is of size n by 1, then the output file should store the result
Kv of size n by 1.

**Comment by ruoxi-wang** [comment]
We also have a MATLAB interface for BBFMM3D for MATLAB users:
https://github.com/ruoxi-wang/mexBBFMM3D

**Comment by vktsn0303** [comment]
Hello ruoxi,
Thank you for your reply. That makes a lot things clear to me for now. 
Also, thanks for letting me know of the existence of mexBBEMM3D.
